server:
  address: 192.168.0.103
  port: 8089
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      register-mbeans: false
      pool-name: 光连接池
      connection-test-query: select 1
      connection-timeout: 1000
      initialization-fail-fast: true
      validation-timeout: 6000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
        enabled: true
        fail-fast: false
  application:
    name: chapter5