server:
  address: 192.168.0.103
  port: 8088
spring:
  application:
    name: chapter6
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
         maximum-pool-size: 100
         minimum-idle: 10
         register-mbeans: false
         pool-name: 光连接池
         connection-test-query: select 1
         connection-timeout: 1000
         initialization-fail-fast: true
         validation-timeout: 6000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
        enabled: true
        fail-fast: false
  devtools:
    restart:
      enabled: true
      additional-paths: Chapter6/src/main/java
      exclude: webapp
feign:
  compression:
    request:
      mime-types: text/html,application/xml,application/json
  httpclient:
    connection-timeout: 2000
    max-connections: 200
    enabled: true
# 设置连接超时时间
ribbon:
  ConnectTimeout: 600
# 设置读取超时时间
  ReadTimeout: 6000
# 对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
# 切换实例的重试次数
  MaxAutoRetriesNextServer: 2
# 对当前实例的重试次数
  MaxAutoRetries: 1
hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 2000
management:
  cloudfoundry:
    enabled: true
  security:
    enabled: false
endpoints:
  shutdown:
    #开启shutdown端点
    enabled: true
logging:
  config: classpath:logback.xml
  register-shutdown-hook: true
  level: error
